apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pokeapi
  name: pokeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
      - image: sahat850/pokeapi:latest
        name: pokeapi
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "250m"
            memory: "250Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pokeapi
  name: pokeapi
spec:
  ports:
  - name: "pokeapi"
    port: 80
    targetPort: 8080
  selector:
    app: pokeapi
  type: LoadBalancer

---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: pokeapi-ssl-certificate
# data:
#   tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUrRENDQStDZ0F3SUJBZ0lTQklUcU9aa3p6cXJDc0FYdUZyVUROdXc4TUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlOREF5TWpNd01UQTFNak13TVRBMU16RmFNQmt4RnpBVkJnTlZCQU1NRGlvVW1WME1JRUpJekFOCkFRRUJCQUlMQ1FZRFZRUUdFd0pWVXpFUk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0NBUThBTUlJQkNnS0NBd0UReEFFT28KbGJ2OSs2L1dvT09rMUdRWTllU0dlTGVSN0FpNUlWUitxVU9Ta1JTVVlSTnoxS0k3aTZLdWdacmpGU3k0S3ZNbQpZTVBXbGFEeTlNbnhtUkdrUGhTblN3RytQM3FNUU1UbStkR0t3Vi9KazBZSE5yenF3VDhkVFBkUzREOWNoUUpQCnJ4SXZySDJ4UjNOeS93em0rcWtRb2d0ZkI2WU05bXc0eHdjRFMyaHNSK1FMTjZ6eHAxeWdCUCtmTlE5NTAvUngKQk5pc1oyRUUvYU55WUE0eFBGUEdDWGpEZU8xMWlHV3RDWFh4Nm5BZVpjWlplMU84cHpPU2xob3U4aEJEWU5ITgpQODZrUEVMMmtCekpXaVpFaXhCM0ZvenJqMXFVUXZFS2lvMXJHVi9iaDNTTTU5TGEvWExGZ0tlekVrbkxDZUF1CnBSWjd6QytGdXA4SzZmN29BeHJjcndJREFRQUJBb0lCQVFEQWdXZ01CMEdBd0lCQWdJRklvQUVnZ0FJbGpBTVQKQkRZVUlnV0JkSGU2a3c4c3NxMkZoaW9uSUx3S1BzQ1BSU1dLQkFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTQpCZ05WSFNNRUdEQVdnQlFVTHJNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlOREF5TWpNd01UQTFNekphRncweU5EQTFNam93TVEwCmRIa3hNekF1TVRBeE1UQTFNam93TVEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDQVd2bXdFQi93em0rcWtRb2cKTURvZ0xRdFJlYXNCeXlpZ0h2dmM2bUZwYlZoUlVXNUJvaWZ4MnRYQm0wZnhrQVNDZ2txaGtpRzl3MEJBUXNGQUFPQgo0SUJBUURBZ1FDTUIwR0ExVWREZ1FXQkJSbFVYK2JZWWJYeUZBUXhRb2xidjkrNi9Xb09PazFHUVk5ZU1HZUxlUjdBaTVJCkIrcVVPU2tSU1VZUk56N2k2S3VnWnpGU3k0S3ZNbW9ZTVBXbGFEeTlNbnhtUkdrUGhTblN3RytQM3FNUU1UbStkR0sKT3dWL0prMFkxRHpBbkE3RFFXa05DMEtKdmd4NW92cndXN2liRTR1TXc3cCtvSGpvcEJBcU5KS0FoT3RNR3dTSgpSZEpDMzFmWUtzdmVNdXZwWGxBRHZzUHdVTUxnTWZUVThWTXhIbDBmY2thMFZtR2JYeFJidDl4V09xaEFKNWlSCjRKMWtSbGZkR0lOSDNUcThEVzVZYUdRM2tXVzIxVzNqRHF4a3U2N0QvWVFGM0h1V1VVQUx1UDZhaWpES3dYcWcKZ0dBd0lCQUFJUUloZ0tJNndhU0pnNWs1Q0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWREZ1FXCkJybUVRVUZ4TUpZb0RtOXZkUzVzU1c5dFpXNTBaWEp6YVhSb2IySnBiR3c5L2IyQm9iMllnWm1WeWIzSnZkWEp5WldSbApCRU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNWXdCbHlIaVNRbWtPYmdreC9uQ2wzVVZySDZKTXNVT1NsOG8zNlExCkQKRXNpWUxvTk1ERXN5N3dtc3hEM3A4eCtBRVdzdXZBR1dIcVhJU0RlYjViS1dkb2J5QUp3WWxxRGs5YU94bFFxbnkKOFM0WWtzd3JqZzJkMW0vQ1JYcFRGbCswRDRuWmF6dUdrQjRvdz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
#   tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeFFPb2xidjkrNi9Xb09PazFHUVk5ZU1HZUxlUjdBaTVJVlIrcVVPU2tSU1VZUk56CjdpNkt1Z1p6RlN5NEt2TW1ZTVBXbGFEeTlNbnhtUkdrUGhTblN3RytQM3FNUU1UbStkR0t3Vi9KazBZSE5yenEKd1Q4ZFRQZFM0RDljaFFKUHJ4SXZySDJ4UjNOeS93em0rcWtRb2d0ZkI2WU05bXc0eHdjRFMyaHNSK1FMTjZ6eApwMXlnQlArZk5ROTUwL1J4Qk5pc1oyRUUvYU55WUE0eFBGUEdDWGpEZU8xMWlHV3RDWFh4Nm5BZVpjWlplMU84CnB6T1NsaG91OGhCRFlOSE5QODZrUEVMMmtCekpXaVpFaXhCM0ZvenJqMXFVUXZFS2lvMXJHVi9iaDNTTTU5TGEvWExGZ0tlekVrbkxDZUF1CnBSWjd6QytGdXA4SzZmN29BeHJjcndJREFRQUJBb0lCQVFEQVZXNERuOSs0RWxYSwpBL01xbGYzNExvWm0yMjlOcXNaeFQzZkg3dnZyUHRnTVhWMVVNCllPcFVCcVJsWExMR0cxSmdMVkFVQzJpa3FYRi9LY1hhQVhlOHRocnhCY1plaE51cEQzUVNqRnpSdGcvYzFGbXEKQnQrbjMvOXVjcUw2OTZ4KzNubDJFVzhEeUxEY2IzM0N2THljTlY4Y0xlbEtFblhOeW1vQ1N3SjdIb1pOYktReAp1VkM1cENjWmJiSk0zN3p4SmtFbzlXalN3M3d4ZzRkaG9tQnJ0aTlRdVJtU2YvZlJlZEJ6b25kSm5CU2N1OUh2U1NrCkNtbm1mc1NlZmlCQU9wVmZKTnNIOW8zTnpXcjJ2R3AvQTh6L1NleE0xbUVXa3k2Y0U1c0poN1phZThRMWRadkFJWUoKeGxIb21RUnNpd3RvYXp6UDVNZnI1eDVUOElRRkI2Vzl3WUxvRUtBdFRQYjhuWUFtNEF1TVVwNWt3ZHp5MWZheApLa1NvaDl1NW9STVFicnBxeE9xRm5NalQ4UGNzRHZCb2RxR2o2OERndGNlbWhkQ1BoNjZ1YUwwVEh4MjFVRXU0CmFGCmxLaXJUSXduTGc3cDgxL1NpWmpaZG9vS3BDbndURDZENENXeStBRGtYOHFTdGFvYXlxRjVQa0lLY3A5TVkvYUwKWHpkV2ZVbStqSzNXUHhEa3hINm1qdTJ5TGcyNWxwT2dud1NpM0N4K0JOM3lDS0lta1lTdVhIQkViQmNRK2Y1Vgp0MUN0RlBBN0RoL0RzUzZGMEd2LzRFR3JKaWpkcGxwazBQRXd3WTVYK0RnZ0dEQ0p3YjNZT0h4TzBpeEt2b2xuNzZyCjlrb3c4c2pqZTh6eXc4NkJnMFFCU2s2WlU5TlprUDc1YjNnPT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K

# Ingress for HTTPS
# Ingress for HTTPS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokeapi-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - netdin.my.id  # Your domain name
    secretName: my-tls-secret  # Your secret name
  rules:
  - host: netdin.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pokeapi
            port:
              number: 80
